version: "3"

services:
  database:
    container_name: database_api
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=tesla
      - POSTGRES_PASSWORD=teslaengenharia
      - POSTGRES_DB=tesla
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    container_name: redis_api
    image: redis:alpine
    ports:
      - 6379:6379

  api:
    container_name: adonis_api
    build: .
    ports:
      - 3333:3333
    command: npm run start
    volumes:
      - .:/usr/api
    depends_on:
      - database
      - redis
    environment:
      - DB_HOST=database
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  pg_data:
